import {esc} from './ui.js';
import config from './config.js';
const consult=(name,price='')=>`<a class="button" target="_blank" rel="noopener" href="${esc('https://wa.me/'+config.whatsapp+'?text='+encodeURIComponent('Hola VIRTUS, quisiera consultar '+name+(price?' a '+price+' por bobina':'')+'. Por favor confirmen opciones y disponibilidad.'))}">${price?price+' · ':''}Consultar por WhatsApp <i class="fas fa-arrow-right"></i></a>`;

export function filamentIntro(){return `<div class="filament-intro"><div><span class="eyebrow">DISTRIBUIMOS FILAMENTOS SKP3D</span><h1>Ideas increíbles. <br>Color en cada capa.</h1><p>Desde un prototipo hasta esa figura que imaginaste: encuentra el color que hace tu proyecto único.</p><a class="button" href="#/producto/filamento-skp3d-pla">Elegir mi filamento <i class="fas fa-arrow-right"></i></a></div><img src="./assets/skp-pla.webp" alt="Bobina de filamento PLA rojo del catálogo SKP3D"></div>`;}

export function declarations(){return `<section class="filament-standards"><span class="eyebrow">INFORMACIÓN DEL PROVEEDOR · PLA</span><h2>Certificaciones y normativas declaradas</h2><div class="service-project-grid"><article><h3>ISO 5425:2023</h3><p>Norma citada por SKP3D en la ficha de su PLA.</p></article><article><h3>RoHS</h3><p>Cumplimiento declarado por SKP3D para este producto.</p></article><article><h3>Seguridad y compostaje industrial</h3><p>SKP3D publica esta declaración general sin identificar una norma adicional.</p></article></div><p class="small">Estas declaraciones corresponden a la ficha del PLA; no se extienden automáticamente a otros materiales. No se han verificado certificados independientes ni su alcance por lote. El compostaje industrial no equivale al compostaje doméstico.</p><a class="text-link" href="https://skp3d.com/product/pla/" target="_blank" rel="noopener">Consultar la declaración de SKP3D <i class="fas fa-arrow-right"></i></a></section>`;}

export function colorOptions(p){if(!p.colors?.length)return '';return `<div class="filament-options"><h2>Tu proyecto, tu color.</h2><div class="color-palette">${p.colors.map(c=>`<span><i style="--swatch:${esc(c.hex)}" aria-hidden="true"></i>${esc(c.name)}</span>`).join('')}</div><label for="product-color">Color para tu pedido</label><select id="product-color">${p.colors.map(c=>`<option>${esc(c.name)}</option>`).join('')}</select><small>Tonos orientativos del catálogo SKP3D. Confirmamos existencias, presentación y color antes del pago.</small></div>`;}

export function finishes(){return `<section class="filament-standards"><span class="eyebrow">EXPLORA OTROS ACABADOS DEL CATÁLOGO SKP3D</span><h2>Más formas de darle personalidad.</h2><div class="service-project-grid"><article><h3>PLA Silk</h3><p>Amarillo, azul, blanco, cobre, dorado, morado, rosa, turquesa y verde.</p><a class="text-link" href="https://skp3d.com/product/pla-silk/" target="_blank" rel="noopener">Ver colores del proveedor <i class="fas fa-arrow-right"></i></a><p>${consult('PLA Silk SKP3D')}</p></article><article><h3>PLA Pastel</h3><p>Amarillo, azul, morado, rosa, tierra y verde.</p><a class="text-link" href="https://skp3d.com/product/pla-pastel/" target="_blank" rel="noopener">Ver colores del proveedor <i class="fas fa-arrow-right"></i></a><p>${consult('PLA Pastel SKP3D')}</p></article><article><h3>HYPER</h3><p>Línea de alta velocidad en PLA, PETG y ABS. Azul, blanco, gris, negro, rojo y verde militar; la combinación depende del material.</p><a class="text-link" href="https://skp3d.com/product/hyper/" target="_blank" rel="noopener">Ver opciones del proveedor <i class="fas fa-arrow-right"></i></a><p>${consult('filamento HYPER SKP3D')}</p></article></div></section>`;}

export function printerGuide(){return `<section class="filament-standards"><span class="eyebrow">TAMBIÉN PODEMOS ASESORARTE</span><h2>Creality K2 Plus Combo</h2><p>Para proyectos de mayor formato: volumen de 350 × 350 × 350 mm, velocidad máxima de 600 mm/s y cámara calefactada. El Combo incluye un CFS para cuatro colores; llegar a 16 requiere cuatro unidades CFS en total.</p><p>Precio: $2.386,40. La velocidad efectiva depende del material y del perfil de impresión.</p><a class="text-link" href="https://skp3d.com/product/creality-k2-plus/" target="_blank" rel="noopener">Ficha SKP3D <i class="fas fa-arrow-right"></i></a> · <a class="text-link" href="https://www.creality.com/products/creality-k2-plus-cfs-combo" target="_blank" rel="noopener">Ficha del fabricante <i class="fas fa-arrow-right"></i></a><p>${consult('Creality K2 Plus Combo')}</p></section>`;}
