import {esc,icon} from './ui.js';
import config from './config.js';
const offerings=[
 {slug:'impresion-3d',name:'Impresión 3D',tag:'DA FORMA A TU IDEA',icon:'box',copy:'Fabricamos prototipos, repuestos plásticos y piezas personalizadas con nuestra Creality K2 Combo. De una idea para tu proyecto a una pieza que puedes usar.',cta:'Cotizar impresión 3D',items:['Diseño o archivo de referencia','Medidas y cantidad de piezas','Material o acabado deseado'],message:'Hola VIRTUS, quisiera cotizar un servicio de impresión 3D.\nProyecto:\nMedidas:\nCantidad:\nMaterial o acabado deseado:\nFecha deseada:\nLes compartiré mi archivo o referencia por este chat.'},
 {slug:'corte-laser',name:'Corte láser',tag:'DEL DISEÑO A LA PIEZA',icon:'bolt',copy:'Realizamos corte y grabado con nuestra Creality Falcon A1 Pro: decoración, señalética, maquetas, regalos y piezas a medida en madera y acrílicos compatibles.',cta:'Cotizar corte láser',items:['Diseño o imagen de referencia','Material y espesor a consultar','Medidas y cantidad de piezas'],message:'Hola VIRTUS, quisiera cotizar un servicio de corte láser.\nProyecto:\nMaterial y espesor:\nMedidas:\nCantidad:\nFecha deseada:\nLes compartiré mi diseño o referencia por este chat.'},
 {slug:'impresoras-3d',name:'Impresoras 3D',tag:'CREA DESDE TU PROPIO ESPACIO',icon:'grid',copy:'Encuentra una impresora 3D para tus ideas, tu aula o tu taller. Consulta modelos, precios y disponibilidad con nuestro equipo.',cta:'Ver impresoras 3D',items:['Cuéntanos qué quieres imprimir','Indica tu presupuesto aproximado','Consulta modelos y disponibilidad'],message:'Hola VIRTUS, estoy interesado/a en comprar una impresora 3D.\nUso previsto (personal, aula o taller):\nQué quiero imprimir:\nPresupuesto aproximado:\n¿Me pueden compartir los modelos, precios y disponibilidad?'}
];

const projects={
 'impresion-3d':{image:'k2-combo-service.png',alt:'Ilustración de impresora Creality K2 Combo con sistema CFS',label:'CREALITY K2 COMBO',title:'¿Qué podemos imprimir para ti?',groups:[['Prototipos y desarrollo','Prueba formas, encajes y conceptos antes de fabricar tu diseño final.'],['Repuestos plásticos','Tapas, perillas, soportes, separadores y adaptadores a medida. Revisamos medidas, esfuerzo y temperatura de uso.'],['Robótica y electrónica','Carcasas para placas, soportes para sensores, chasis y piezas para tus mecanismos.'],['Maquetas y educación','Modelos arquitectónicos, figuras geométricas y recursos didácticos para aprender haciendo.'],['Organización y accesorios','Organizadores, bases para dispositivos, soportes y soluciones para tu escritorio o taller.'],['Personalización y multicolor','Llaveros, nombres, figuras decorativas y detalles de marca. Consulta los colores disponibles para tu diseño.']],note:'Elegimos material, orientación y acabado según el uso de la pieza. Las dimensiones, tolerancias, colores y viabilidad se confirman al revisar tu proyecto; las piezas grandes pueden requerir división y ensamblaje.'},
 'corte-laser':{image:'falcon-a1-pro.png',alt:'Ilustración de cortadora y grabadora láser Creality Falcon A1 Pro',label:'CREALITY FALCON A1 PRO',title:'Diseños que toman forma.',groups:[['Madera y MDF','Letras, siluetas, paneles decorativos, cajas y piezas para ensamblar. Consulta el tipo de madera y espesor adecuados.'],['Acrílico','Letreros, placas, nombres, bases, exhibidores y piezas decorativas. Revisamos color, transparencia y espesor según el equipo.'],['Grabado personalizado','Nombres, logotipos y diseños sobre materiales compatibles para regalos y detalles de marca.'],['Maquetas y proyectos','Piezas para modelos arquitectónicos, prototipos planos y estructuras de encaje.'],['Eventos y emprendimientos','Identificadores, recuerdos, toppers decorativos, números de mesa y señalética para tu negocio.'],['Material educativo','Rompecabezas, letras, figuras y recursos para actividades de aprendizaje.']],note:'Cada trabajo se cotiza según diseño, material, espesor, tamaño y cantidad. Confirmamos compatibilidad de la madera o del acrílico antes de fabricar; no todos los acabados y espesores se trabajan de la misma manera.'}
};
function projectSections(o){const p=projects[o.slug];if(!p)return '';return `<section class="service-projects"><span class="eyebrow">HECHO PARA TU PROYECTO</span><h2>${p.title}</h2><div class="service-project-grid">${p.groups.map(([name,text],i)=>`<article><span class="eyebrow">0${i+1}</span><h3>${name}</h3><p>${text}</p></article>`).join('')}</div><p class="service-process-note">${p.note}</p><div class="service-process"><div><strong>01 · Comparte tu idea</strong><p>Envíanos un archivo, medidas o una imagen de referencia por WhatsApp.</p></div><div><strong>02 · Revisamos y cotizamos</strong><p>Confirmamos el diseño, material, precio y fecha de entrega.</p></div><div><strong>03 · Fabricamos para ti</strong><p>Con tu aprobación, preparamos el trabajo acordado.</p></div></div><a class="button whatsapp-order" target="_blank" rel="noopener" href="${esc(`https://wa.me/${config.whatsapp}?text=${encodeURIComponent(o.message)}`)}">Cuéntanos tu proyecto ${icon('arrow')}</a></section>`;}

export function serviceCards(){return `<section class="wrap services-section"><div class="section-heading"><div><span class="eyebrow">MÁS FORMAS DE CREAR</span><h2>De la idea al mundo real.</h2></div></div><div class="services-grid">${offerings.map(o=>`<a class="service-card" href="#/${o.slug}">${projects[o.slug]?`<img class="service-card-art" src="./assets/${projects[o.slug].image}" alt="${projects[o.slug].alt}" loading="lazy">`:`<img class="service-card-art" src="./assets/sparkx-i7-combo.png" alt="SPARKX i7 Color Combo con CFS Lite" loading="lazy">`}<span class="eyebrow">${o.tag}</span><h3>${o.name}</h3><p>${o.copy}</p><span class="text-link">${o.cta} ${icon('arrow')}</span></a>`).join('')}</div></section>`;}
export function servicePage(path){const o=offerings.find(o=>'/'+o.slug===path);if(!o)return null;return `<section class="wrap static-detail"><a class="text-link" href="#/">← Volver al inicio</a><div class="glass-detail service-detail"><div class="service-visual">${projects[o.slug]?`<img class="service-hero-art" src="./assets/${projects[o.slug].image}" alt="${projects[o.slug].alt}"><span class="service-machine-label">${projects[o.slug].label}</span><small>Imagen ilustrativa</small>`:`${icon(o.icon)}<span>IMAGINA.<br>DISEÑA.<br>CREA.</span>`}</div><div><span class="eyebrow">${o.tag}</span><h1>${o.name}</h1><p>${o.copy}</p><h2>${o.slug==='impresoras-3d'?'Encuentra tu próxima impresora':'Preparemos tu cotización'}</h2><ul>${o.items.map(i=>`<li>${i}</li>`).join('')}</ul><a class="button whatsapp-order" target="_blank" rel="noopener" href="${esc(`https://wa.me/${config.whatsapp}?text=${encodeURIComponent(o.message)}`)}">${o.cta} ${icon('arrow')}</a><p class="small service-note">${o.slug==='impresoras-3d'?'Modelos, precios y condiciones se confirman por WhatsApp.':'El precio y el plazo se confirman después de revisar tu diseño. Adjunta los archivos directamente en WhatsApp.'}</p></div></div>${projectSections(o)}</section>`;}
