import {esc,icon} from './ui.js';
import config from './config.js';
const offerings=[
 {slug:'impresion-3d',name:'Impresión 3D',tag:'DA FORMA A TU IDEA',icon:'box',copy:'Convierte tu diseño en una pieza. Cuéntanos qué necesitas fabricar y solicita una cotización para tu proyecto.',cta:'Cotizar impresión 3D',items:['Diseño o archivo de referencia','Medidas y cantidad de piezas','Material o acabado deseado'],message:'Hola VIRTUS, quisiera cotizar un servicio de impresión 3D.\nProyecto:\nMedidas:\nCantidad:\nMaterial o acabado deseado:\nFecha deseada:\nLes compartiré mi archivo o referencia por este chat.'},
 {slug:'corte-laser',name:'Corte láser',tag:'DEL DISEÑO A LA PIEZA',icon:'bolt',copy:'Dale forma a tus proyectos con corte láser. Comparte tu diseño para revisar el material, el espesor y los detalles del trabajo.',cta:'Cotizar corte láser',items:['Diseño o imagen de referencia','Material y espesor a consultar','Medidas y cantidad de piezas'],message:'Hola VIRTUS, quisiera cotizar un servicio de corte láser.\nProyecto:\nMaterial y espesor:\nMedidas:\nCantidad:\nFecha deseada:\nLes compartiré mi diseño o referencia por este chat.'},
 {slug:'impresoras-3d',name:'Impresoras 3D',tag:'CREA DESDE TU PROPIO ESPACIO',icon:'grid',copy:'Encuentra una impresora 3D para tus ideas, tu aula o tu taller. Consulta modelos, precios y disponibilidad con nuestro equipo.',cta:'Consultar impresoras 3D',items:['Cuéntanos qué quieres imprimir','Indica tu presupuesto aproximado','Consulta modelos y disponibilidad'],message:'Hola VIRTUS, estoy interesado/a en comprar una impresora 3D.\nUso previsto (personal, aula o taller):\nQué quiero imprimir:\nPresupuesto aproximado:\n¿Me pueden compartir los modelos, precios y disponibilidad?'}
];
export function serviceCards(){return `<section class="wrap services-section"><div class="section-heading"><div><span class="eyebrow">MÁS FORMAS DE CREAR</span><h2>De la idea al mundo real.</h2></div></div><div class="services-grid">${offerings.map(o=>`<a class="service-card" href="#/${o.slug}"><span class="service-symbol">${icon(o.icon)}</span><span class="eyebrow">${o.tag}</span><h3>${o.name}</h3><p>${o.copy}</p><span class="text-link">${o.cta} ${icon('arrow')}</span></a>`).join('')}</div></section>`;}
export function servicePage(path){const o=offerings.find(o=>'/'+o.slug===path);if(!o)return null;return `<section class="wrap static-detail"><a class="text-link" href="#/">← Volver al inicio</a><div class="glass-detail service-detail"><div class="service-visual" aria-hidden="true">${icon(o.icon)}<span>IMAGINA.<br>DISEÑA.<br>CREA.</span></div><div><span class="eyebrow">${o.tag}</span><h1>${o.name}</h1><p>${o.copy}</p><h2>${o.slug==='impresoras-3d'?'Encuentra tu próxima impresora':'Preparemos tu cotización'}</h2><ul>${o.items.map(i=>`<li>${i}</li>`).join('')}</ul><a class="button whatsapp-order" target="_blank" rel="noopener" href="${esc(`https://wa.me/${config.whatsapp}?text=${encodeURIComponent(o.message)}`)}">${o.cta} ${icon('arrow')}</a><p class="small service-note">${o.slug==='impresoras-3d'?'Modelos, precios y condiciones se confirman por WhatsApp.':'El precio y el plazo se confirman después de revisar tu diseño. Adjunta los archivos directamente en WhatsApp.'}</p></div></div></section>`;}
